💅 Show an explanatory banner when re-running

diff --git a/.github/workflows/reusable-tox.yml b/.github/workflows/reusable-tox.yml
--- a/.github/workflows/reusable-tox.yml
+++ b/.github/workflows/reusable-tox.yml
@@ -409,6 +409,24 @@ jobs:
         && steps.tox-run.outputs.codecov-flags != 'MyPy'
       run: >-
         cat code-coverage-results.md >> "${GITHUB_STEP_SUMMARY}"
+    - name: Explain re-runing the failing tests
+      if: >-
+        !cancelled()
+        && steps.tox-run.outcome == 'failure'
+        && inputs.tox-rerun-posargs != ''
+      run: >-
+        {
+          echo '> [!IMPORTANT]';
+          echo '> The main tox command failed. It has been restarted with';
+          echo '> maximum context extraction to help you troubleshoot the';
+          echo '> issue. We have intentionally marked the second run as';
+          echo '> failing. Be sure to carefully compare the first and the';
+          echo '> second invocations to learn if the tests are flaky and';
+          echo '> hopefully guide you in fixing them. Cheers! 💛💙'
+          echo;
+          echo;
+        } | tee -a "${GITHUB_STEP_SUMMARY}"
+      shell: bash -eEuo pipefail {0}
     - name: Re-run the failing tests with maximum verbosity
       if: >-
         !cancelled()
